AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false