AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: false

Style/StringLiterals:
  Enabled: false
